# Due to membarrier system call requires docker 20.10.0 or higher to be deployed without customizing docker
version: '3.8'

services:
  app:
    image: jlesage/firefox:v1.17.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
      USER_ID: 0
      GROUP_ID: 0
      UMASK: 022
      TZ: Europe/Amsterdam
      ENABLE_CJK_FONT: 1
    dns:
      - 1.1.1.1
      - 1.0.0.1
    networks:
      - portainerce_net
    ports:
      - target: 5800
        published: 5801
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: config
        target: /config
      - type: bind
        source: /share/Scratch
        target: /storage
# Set container shared memory size to 2GB
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 2147483648

networks:
  portainerce_net:
    external: true

volumes:
  config:
