version: '3.8'

services:
  app:
    image: mikenye/picard:2.6.2
    environment:
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
      USER_ID: 0
      GROUP_ID: 0
      UMASK: 022
      TZ: Europe/Amsterdam
      ENABLE_CJK_FONT: 1
    volumes:
      - config:/config:rw
      - storage:/storage:rw
      - /share/Data:/storage/data:rw
      - /share/Downloads:/storage/downloads:rw
      - /share/Attic:/storage/attic:rw
      - /share/Music:/storage/music:rw
    dns:
      - 1.1.1.1
      - 1.0.0.1
    networks:
      - portainerce_net
    ports:
      - target: 5800
        published: 5802
    deploy:
      mode: replicated
      replicas: 1

networks:
  portainerce_net:
    external: true

volumes:
  config:
  storage:
