version: '3.8'

services:
  ui:
    image: ghcr.io/linuxserver/qbittorrent:version-14.3.6.99202107121017-7389-3ac8c97e6ubuntu20.04.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PUID: 0
      PGID: 0
      UMASK_SET: 022
      TZ: Europe/Amsterdam
      WEBUI_PORT: 8080
    dns:
      - 1.1.1.1
      - 1.0.0.1
    networks:
      - qbt-net
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: config
        target: /config
      - type: bind
        source: /share/Scratch
        target: /downloads

networks:
  qbt-net:
    external: true

volumes:
  config:
